/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData _12 = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData _13 = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData headset = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart_circle = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData home_filled = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData home_outline = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData music = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData _3 = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData _5 = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData _6 = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData _8 = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData _10 = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData left_open = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData heart_empty = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData setting_filled =
      IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData setting_outline =
      IconData(0xe810, fontFamily: _kFontFam);
  static const IconData play_circle = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData forward_5 = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData replay_5 = IconData(0xe814, fontFamily: _kFontFam);
}
